<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

# Data Investigation with Pandas

## 1.0 Importing our Libraries

In [ ]:
# Importing the libraries we will need 
import csv
# Importing the pandas library
# 
import pandas as pd

# Importing the numpy library
#
import numpy as np

## 1.1 Reading the Dataset from our CSV file



The dataset we will use contains information about the 2009 Census - The Rural Urban Population by Age, Sex and District.


*   Dataset link for download or access: [Link](https://drive.google.com/open?id=1pc9ZLFGsosdWBk1lI29ADIqRtCvD_FBe)

In [ ]:
# Let's read the data from the CSV file and create the dataframe to be used
# 

with open('Rural_Urban_Population_By_Age_Sex_and_by_District__2009.csv','r') as f:
    rural_urban= pd.read_csv(f,index_col=0, encoding='utf-8')

## 1.2 Previewing our Dataset

In [ ]:
# Let's preview the first 10 rows of our data
# 
rural_urban.head(10)

             Urban/Rural Age_years   Male  ...   County  Province OBJECTID
District                                   ...
NAIROBI WEST       Urban         0  10126  ...  Nairobi   NAIROBI        0
NAIROBI WEST       Urban         1   8124  ...  Nairobi   NAIROBI        1
NAIROBI WEST       Urban         2   8462  ...  Nairobi   NAIROBI        2
NAIROBI WEST       Urban         3   8334  ...  Nairobi   NAIROBI        3
NAIROBI WEST       Urban         4   7948  ...  Nairobi   NAIROBI        4
NAIROBI WEST       Urban         5   7547  ...  Nairobi   NAIROBI        5
NAIROBI WEST       Urban         6   6966  ...  Nairobi   NAIROBI        6
NAIROBI WEST       Urban         7   6511  ...  Nairobi   NAIROBI        7
NAIROBI WEST       Urban         8   6171  ...  Nairobi   NAIROBI        8
NAIROBI WEST       Urban         9   6361  ...  Nairobi   NAIROBI        9

[10 rows x 8 columns]

## 1.3 Accessing Information about our Dataset

In [ ]:
# We can getting to know more about the dataset by accessing its information 
#
rural_urban.describe()

               Male        Female         Total      OBJECTID
count  25420.000000  25420.000000  25420.000000  25420.000000
mean     755.014083    763.872502   1518.886585  12709.500000
std     1305.988549   1295.903980   2589.418161   7338.266258
min        0.000000      0.000000      0.000000      0.000000
25%       57.000000     54.000000    112.000000   6354.750000
50%      269.500000    281.000000    555.000000  12709.500000
75%      891.000000    950.000000   1849.250000  19064.250000
max    23060.000000  23090.000000  44473.000000  25419.000000

## 1.4 Answering Questions

Let's answer the following questions with our dataset

In [ ]:
# Challenge 1
# What was the average age of a person of Kenya?



#change the Age_years datatype from str to int
rural_urban.replace(80+, 80)
rural_urban["Age_years"]= rural_urban["Age_years"].astype['int']

rural_urban= pd.DataFrame(rural_urban)
mean= rural_urban["Age_years"].mean()
print(mean)

In [ ]:
rural_urban.info()

In [ ]:
# Challenge 2
# What was the average female population in Kenya?
#
Female_mean = rural_urban['Female'].mean()
print(Female_mean)

763.8725019669552

In [ ]:
# Challenge 3
# What was the average male population in Kenya?
#
Male_mean = rural_urban['Male'].mean()
print(Male_mean)

755.0140833988985

In [ ]:
# Challenge 4
# Which 5 districts were the most densely populated Kenya in descending order?
#

sorted=rural_urban.sort_values(by='Total', ascending=False)
sorted[['District', 'Total']].head(5)

In [ ]:
# Challenge 5
# Which 5 counties were the most densely populated Counties in descending order?
# 
sorted=rural_urban.sort_values(by='Total', ascending=False)
sorted[['County', 'Total']].head(5)

                County  Total
District
NAIROBI EAST   Nairobi  44473
NAIROBI EAST   Nairobi  41997
NAIROBI NORTH  Nairobi  40812
NAIROBI EAST   Nairobi  38813
NAIROBI EAST   Nairobi  38183

In [ ]:
# Challenge 6
# Which 5 districts were the most sparsely populated in descending order?
# 
sorted=rural_urban.sort_values(by='Total', ascending=False)
sorted[['County', 'Total']].tail(5)

                   County  Total
District
POKOT CENTRAL  West Pokot      0
POKOT CENTRAL  West Pokot      0
POKOT CENTRAL  West Pokot      0
POKOT CENTRAL  West Pokot      0
SAMIA               Busia      0

In [ ]:
# Challenge 7
# What was the average population of the the most densely populated county in Kenya?
# 
County_sum = pd.DataFrame(rural_urban.groupby('County') ['Total'].sum())
print(County_sum)
s= County_sum.max()

                   Total
County
Baringo           555561
Bomet             891835
Bungoma          1375063
Busia             743946
Elgeyo Marakwet   369998
Embu              516212
Garissa           623060
Homa Bay          963794
Isiolo            143294
Kajiado           687312
Kakamega         1660651
Kericho           590690
Kiambu           1673785
Kilifi           1109735
Kirinyaga         528054
Kisii            1263559
Kisumu            968909
Kitui            1012709
Kwale             649931
Laikipia          399227
Lamu              101539
Machakos         1098584
Makueni           884527
Mandera          1025756
Marsabit          291166
Meru             1591533
Migori            917170
Mombasa           939370
Murang'a          892078
Nairobi          3138369
Nakuru           1603325
Nandi             752965
Narok             850920
Nyamira           486975
Nyandarua         596268
Nyeri             693558
Samburu           223947
Siaya             842304
Taita Taveta      284657
Tana River        240075
Tharaka Nithi     130098
Trans Nzoia       818757
Turkana           855399
Uasin Gishu       894179
Vihiga            554622
Wajir             661941
West Pokot        512690
Total    3138369
dtype: int64

In [ ]:
# Challenge 8
# What was the average population of the the most sparsely populated county in Kenya?
# 
County_sum = rural_urban.groupby('County') ['Total'].sum()
print(County_sum)
County_sum.min()

County
Baringo             555561
Bomet               891835
Bungoma            1375063
Busia               743946
Elgeyo Marakwet     369998
Embu                516212
Garissa             623060
Homa Bay            963794
Isiolo              143294
Kajiado             687312
Kakamega           1660651
Kericho             590690
Kiambu             1673785
Kilifi             1109735
Kirinyaga           528054
Kisii              1263559
Kisumu              968909
Kitui              1012709
Kwale               649931
Laikipia            399227
Lamu                101539
Machakos           1098584
Makueni             884527
Mandera            1025756
Marsabit            291166
Meru               1591533
Migori              917170
Mombasa             939370
Murang'a            892078
Nairobi            3138369
Nakuru             1603325
Nandi               752965
Narok               850920
Nyamira             486975
Nyandarua           596268
Nyeri               693558
Samburu             223947
Siaya               842304
Taita Taveta        284657
Tana River          240075
Tharaka Nithi       130098
Trans Nzoia         818757
Turkana             855399
Uasin Gishu         894179
Vihiga              554622
Wajir               661941
West Pokot          512690
Name: Total, dtype: int64

101539

In [ ]:
# Challenge 9
# What was the total population of Busia County? 
# 
County_sum['Busia']

743946

In [ ]:
# Challenge 10
# What was the average age of person in Busia County? How many people of this age were in Busia County?
# 
OUR CODE GOES HERE

In [ ]:
# Challenge 11
# What was the Total population of Teso South District?
# 
District = rural_urban.groupby('District')['Total'].sum
print(District)

<bound method GroupBy.sum of <pandas.core.groupby.generic.SeriesGroupBy object at 0x7fd09fe71ad0>>

In [ ]:
# Challenge 12
# What was the urban population of Teso South District?
# 
TesoSouth_Urban= rural_urban.groupby(['District','Urban/Rural'])['Total'].sum()
TesoSouth_Urban[['Dstrict','Urban/Rural','Total']]

In [ ]:
# Challenge 13
# What was the rural population of Teso South District?
# 
OUR CODE GOES HERE

In [ ]:
# Challenge 14
# What was the population of people aged 60 and above in Kenya?
#
rural_urban(['Age_year']>60)

In [ ]:
# Challenge 15 
# What was the urban population in Kenya?
#
y= rural_urban[(rural_urban['Urban/Rural']=='Urban')& rural_urban['Total']]
print(y)
urban_Total= y['Total'].sum()
print(urban_Total)

             Urban/Rural Age_years  Male  ...   County  Province OBJECTID
District                                  ...
NAIROBI WEST       Urban         1  8124  ...  Nairobi   NAIROBI        1
NAIROBI WEST       Urban         2  8462  ...  Nairobi   NAIROBI        2
NAIROBI WEST       Urban         5  7547  ...  Nairobi   NAIROBI        5
NAIROBI WEST       Urban         7  6511  ...  Nairobi   NAIROBI        7
NAIROBI WEST       Urban         9  6361  ...  Nairobi   NAIROBI        9
...                  ...       ...   ...  ...      ...       ...      ...
TESO SOUTH         Urban        73    14  ...    Busia   WESTERN    12947
TESO SOUTH         Urban        74     8  ...    Busia   WESTERN    12948
TESO SOUTH         Urban        76     7  ...    Busia   WESTERN    12950
TESO SOUTH         Urban        78     3  ...    Busia   WESTERN    12952
TESO SOUTH         Urban    Age NS     9  ...    Busia   WESTERN    12955

[5691 rows x 8 columns]
6103297