<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

## Step 1: Finding and counting missing data

Having known how missing values in a dataset are created, we will now get introduced to how we can work with such a dataset. The first step that we will perform is to find the missing values and know how many they are.

In [2]:
# We will first import our dataset that we will use for the examples. We will do this by first
# Importing our pandas library 
import pandas as pd


# then storing the url location of our dataset to the variable url
url = 'http://bit.ly/TitanicDataset1'

# We will read the dataset from above url and store the dataframe in the variable df
df = pd.read_csv(url)
df.head()

   pclass  survived  ...   body                        home.dest
0     1.0       1.0  ...    NaN                     St Louis, MO
1     1.0       1.0  ...    NaN  Montreal, PQ / Chesterville, ON
2     1.0       0.0  ...    NaN  Montreal, PQ / Chesterville, ON
3     1.0       0.0  ...  135.0  Montreal, PQ / Chesterville, ON
4     1.0       0.0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

In [3]:
# Challenge 1
# In parallel to this, we will also be working with another dataset too. We will use it for practice.

# Let's first store our url location just like we did above
gov_dataset = 'http://bit.ly/GovProjectFinanceDataset1'

# Then read the dataset from url and store it in our variable of choice
# 
gov_dataset = pd.read_csv(gov_dataset)

# And familiarize ourselves with the dataframe by viewing its first 5 rows
# 
gov_dataset.head()

                                 Implementing_Agency  ...  OBJECTID
0                                                NaN  ...         0
1   MOEW&NR  National Environment Management Auth...  ...         1
2   Ministry of Agriculture, Livestock and Fisheries  ...         2
3                                     The Presidency  ...         3
4   MOAL&F  Kenya  Plant Health Inspectorate Serv...  ...         4

[5 rows x 7 columns]

In [4]:
# We count the number of non - missing values in the df dataframe
#
df.count()

pclass       1309
survived     1309
name         1309
sex          1309
age          1046
sibsp        1309
parch        1309
ticket       1309
fare         1308
cabin         295
embarked     1307
boat          486
body          121
home.dest     745
dtype: int64

1310

In [5]:
# Challenge 2: Government Project Dataset
# We also count the number of non - missing values in the our government project dataset
# 
gov_dataset.count()

Implementing_Agency                      39
Total_-_GOK_Budget_Est_KES               39
Total_-_Loan_Budget_Est_KES              40
Total_-_Grant_Budget_Est_KES             40
Total_Budget_Supported__by_Donors_KES    40
Total_2013/2014_Budget_KES               40
OBJECTID                                 40
dtype: int64

In [6]:
# A longer method can be to subtract the no. of non-missing rows from the total number 
# of rows in the dataframe in order to determine the no. of missing values as shown
# 
num_rows = df.shape[0]
num_missing = num_rows - df.count() 
num_missing

pclass          1
survived        1
name            1
sex             1
age           264
sibsp           1
parch           1
ticket          1
fare            2
cabin        1015
embarked        3
boat          824
body         1189
home.dest     565
dtype: int64

In [ ]:
# Challenge 3: Government Project Dataset
# We now also subtract the no. of non-missing rows from the total number of rows 
# to determine the no. of missing values in our government project dataset
#
num_rows=gov_dataset.shape[0]
num_rows
num_missing= num_rows - gov_dataset.count()
num_missing

Implementing_Agency                      1
Total_-_GOK_Budget_Est_KES               1
Total_-_Loan_Budget_Est_KES              0
Total_-_Grant_Budget_Est_KES             0
Total_Budget_Supported__by_Donors_KES    0
Total_2013/2014_Budget_KES               0
OBJECTID                                 0
dtype: int64

In [3]:
# Another method would also be to count the number of missing values in our dataframe,  
# using the count_nonzero function from numpy - and including the isnull() method.

# But before we do that, we would need import numpy,
# 
import numpy as np


# Then count those missing values in our dataframe
#
np.count_nonzero(df.isnull())

3869

In [ ]:
# Challenge 4: Government Project Dataset
# Let's just do what we did in our previous cell. We found out the number of missing values 
# in our dataset using the count_nonzero function from numpy 
#
np.count_nonzero(gov_dataset.isnull())

2

In [ ]:
# We could also count the number of missing values for a particular column by specifying 
# the column by still using the count_nonzero function from numpy 
# 
np.count_nonzero(df['body'].isnull())

1189

In [ ]:
# Challenge 5: Government Project Dataset
# And again specify how many non-missing values we have in the column: Total_-_GOK_Budget_Est_KES	
#
np.count_nonzero(gov_dataset['Total_-_GOK_Budget_Est_KES'].isnull())

1

## Step 2: Clean Missing Data

Now that we have been able to identify our missing values in our datasets, we can deal with them in the following ways.

### a) We can recode/replace these values
Here, we can do this by using the fillna method and recoding/replacing the missing values with another value or other values. In this example, we will recode the missing values to 0.

In [ ]:
# We can recode missing values with 0 by doing the following. 
# Do note that this will appear as 0.0 in your dataframe.
# 
df_recode = df.fillna(0)

# then preview the first 5 rows for the recoded dataframe
#
df_recode.head()

   pclass  survived  ...   body                        home.dest
0     1.0       1.0  ...    0.0                     St Louis, MO
1     1.0       1.0  ...    0.0  Montreal, PQ / Chesterville, ON
2     1.0       0.0  ...    0.0  Montreal, PQ / Chesterville, ON
3     1.0       0.0  ...  135.0  Montreal, PQ / Chesterville, ON
4     1.0       0.0  ...    0.0  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

In [ ]:
# After recoding, let's check for non-missing values in the recoded dataframe
#
np.count_nonzero(df_recode.isnull())

0

In [ ]:
# Challenge 6: Government Project Dataset
# Nice! Let's now replace the missing values in our dataset with 0 again 
# just as in our previous example
# 
gov_recode= gov_dataset.fillna(0)
np.count_nonzero(gov_recode.isnull())

0

**Challenge 7:** Together with your peer now discuss the cases where you might use the above recoding technique.

### b) We can fill forward missing values

When data is filled data forward, the last known value is used for the next missing value. The missing values are replaced with the last known/recorded value. Let's see how that works.

In [ ]:
# First lets preview out df ,and note the missing data in the boat and body columns
#
np.count_nonzero(df[['boat','body']].isnull())

2013

In [ ]:
# And now let's fill forward
#
df_fill_forward = df.fillna(method='ffill')

# Then preview our dataframe and try to understand it
#
#df_fill_forward.head()
df.head()

# Did you notice what happens when the column begins with a missing value? 
# Discuss this with your peer

   pclass  survived  ...   body                        home.dest
0     1.0       1.0  ...    NaN                     St Louis, MO
1     1.0       1.0  ...    NaN  Montreal, PQ / Chesterville, ON
2     1.0       0.0  ...    NaN  Montreal, PQ / Chesterville, ON
3     1.0       0.0  ...  135.0  Montreal, PQ / Chesterville, ON
4     1.0       0.0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

In [ ]:
# Challenge 8: Government Project Dataset
# Onto our other dataset, let's now fill forward the missing values and see what happens
# 

gov_fill_foward = gov_dataset.fillna(method='ffill')

**Challenge 9: **Together with your peer discuss the cases where you might use the above fill forward technique.

### c) We can fill backward missing values

We can also do the opposite, and fill data backward our missing values. When doing this, the newest value replaces the missing data.

In [ ]:
# Again first lets preview df (last 10 items), and note the missing data in the boat and body columns
#
df.head(10)

   pclass  survived  ...   body                        home.dest
0     1.0       1.0  ...    NaN                     St Louis, MO
1     1.0       1.0  ...    NaN  Montreal, PQ / Chesterville, ON
2     1.0       0.0  ...    NaN  Montreal, PQ / Chesterville, ON
3     1.0       0.0  ...  135.0  Montreal, PQ / Chesterville, ON
4     1.0       0.0  ...    NaN  Montreal, PQ / Chesterville, ON
5     1.0       1.0  ...    NaN                     New York, NY
6     1.0       1.0  ...    NaN                       Hudson, NY
7     1.0       0.0  ...    NaN                      Belfast, NI
8     1.0       1.0  ...    NaN              Bayside, Queens, NY
9     1.0       0.0  ...   22.0              Montevideo, Uruguay

[10 rows x 14 columns]

In [ ]:
# And now fill backward
#
df_fill_backward = df.fillna(method='bfill')

# Then preview our dataframe (last 10 items) and try to understand what took place
#
print(df_fill_backward.tail(10))

# After this, we will discuss what happens when a column ends with a missing value.

      pclass  survived  ...   body home.dest
1300     3.0       1.0  ...  312.0       NaN
1301     3.0       0.0  ...  312.0       NaN
1302     3.0       0.0  ...  328.0       NaN
1303     3.0       0.0  ...  328.0       NaN
1304     3.0       0.0  ...  328.0       NaN
1305     3.0       0.0  ...  304.0       NaN
1306     3.0       0.0  ...  304.0       NaN
1307     3.0       0.0  ...    NaN       NaN
1308     3.0       0.0  ...    NaN       NaN
1309     NaN       NaN  ...    NaN       NaN

[10 rows x 14 columns]

In [ ]:
gov_dataset.head()

                                 Implementing_Agency  ...  OBJECTID
0                                                NaN  ...         0
1   MOEW&NR  National Environment Management Auth...  ...         1
2   Ministry of Agriculture, Livestock and Fisheries  ...         2
3                                     The Presidency  ...         3
4   MOAL&F  Kenya  Plant Health Inspectorate Serv...  ...         4

[5 rows x 7 columns]

In [ ]:
# Challenge 10: Government Project Dataset
# Back to our government dataset. We now fill backward the missing values 
# and try to understand the changes that took place
# 
gov_backward_fill= gov_dataset.fillna(method='bfill')
gov_backward_fill.head()

                                 Implementing_Agency  ...  OBJECTID
0   MOEW&NR  National Environment Management Auth...  ...         0
1   MOEW&NR  National Environment Management Auth...  ...         1
2   Ministry of Agriculture, Livestock and Fisheries  ...         2
3                                     The Presidency  ...         3
4   MOAL&F  Kenya  Plant Health Inspectorate Serv...  ...         4

[5 rows x 7 columns]

**Challenge 11: ** Together with your peer discuss the cases where you might use the above fill backward technique.


### d) We can interpolate missing values

Interpolation uses other values to fill in the missing values. It does this by treating missing values as if they should be equally spaced apart. This function fills in the missing values linearly as shown in the example below.

In [ ]:
# Once again first lets print out df, and note the missing data in the boat and body columns
# NB: iloc gets rows (or columns) at particular positions in the index
#
df.iloc[0:10, 11:13].head(10)

  boat   body
0    2    NaN
1   11    NaN
2  NaN    NaN
3  NaN  135.0
4  NaN    NaN
5    3    NaN
6   10    NaN
7  NaN    NaN
8    D    NaN
9  NaN   22.0

In [ ]:
# Then perform our intepolation
#
df_interpolate = df.interpolate().iloc[0:10, 11:13];
df_interpolate.head(10)

  boat        body
0    2         NaN
1   11         NaN
2  NaN         NaN
3  NaN  135.000000
4  NaN  116.166667
5    3   97.333333
6   10   78.500000
7  NaN   59.666667
8    D   40.833333
9  NaN   22.000000

In [ ]:
# Challenge 12: Government Project Dataset
# Intepolate the missing values in our dataset, noting the changes
#
gov_dataset = gov_dataset.interpolate().iloc[0:10,0:10]
gov_dataset.head(10)

                                 Implementing_Agency  ...  OBJECTID
0                                                NaN  ...         0
1   MOEW&NR  National Environment Management Auth...  ...         1
2   Ministry of Agriculture, Livestock and Fisheries  ...         2
3                                     The Presidency  ...         3
4   MOAL&F  Kenya  Plant Health Inspectorate Serv...  ...         4
5                        Ministry of Foreign Affairs  ...         5
6     MRDA  Ewaso Ngiro North Dev. Authority (ENNDA)  ...         6
7   MOE&P  Kenya Electricity Transmission Company...  ...         7
8   Office of The Attorney General and Department...  ...         8
9                 State Department of Infrastructure  ...         9

[10 rows x 7 columns]

**Challenge 13: **Together with your peer discuss the cases where you might use the above interpolate technique.

### e) We can drop/delete missing values

The other way to work with missing data is to drop/delete the records with the missing data. This is a judgement that you have to make based on your research. Sometimes keeping the entire dataset together with the missing values, can leave you with a useless dataset. On the other hand, the missing data many not be random and dropping those missing values would leave you with a biased dataset or deleting the missing dataset might leave you with insufficient data for analysis. All of this we will learn more indepth during the course of the program. 

For now lets see how we can drop missing values from a dataset.

In [ ]:
# Let's find out the size of our dataset
# 
df.shape

(1310, 14)

In [ ]:
# If we were to keep our complete rows; meaning we drop any record with a missing value, then
#
df_dropped = df.dropna()

# We are left with no rows of data
#
df_dropped.shape

(0, 14)

In [ ]:
# Printing out df_dropped
df_dropped

Empty DataFrame
Columns: [pclass, survived, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, boat, body, home.dest]
Index: []

In [ ]:
# Challenge 14: Financial Allocation Dataset
# Let's now drop the records that have missing values
# url = http://bit.ly/MSFinancialDataset
#
Finance = pd.read_csv(url)
Finance.shape
print('Finance shape is', Finance.shape)

Finance_dropped= Finance.dropna()
Finance_dropped.shape
print('Finance_dropped shape', Finance_dropped.shape)

Finance shape is (1310, 14)
Finance_dropped shape (0, 14)

Challenge 15: Together with your peer discuss the cases where you might use the above drop/delete technique.

In [23]:
l = list(range(10))
del l[9]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8]