<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

# Where does Missing Data come from?

In the course of your data science career,  it is rare that you will work with raw data that does not have missing values. 

Missing data can arise from the loading of data, when merging data, data entry or the reindexing process - the process of transforming data from one process to the other. We will see how this can happen in the sections below:

## 1.0 Loading Data

When we load data with pandas, we get a dataframe with the NaN value in the cell that had missing data. This is as a result of the read_csv function, which can take the following parameters which relate to reading in missing values: na_values, keep_default_na and na_filter.

We will now see how these parameters work.

In [ ]:
# First lets import our dataset that we will use for the examples

# Let's import our pandas library 
import pandas as pd

# Let's set the location for our data
url = 'http://bit.ly/UniversityDataSet'

# We then store this dataset in a dataframe
# We us the latin1 encoding because our dataset contains special characters. 
# An encoding is one specific way of interpreting bytes: It's a look-up table that says, 
# for example, that a byte with the value 97 stands for 'a'.
#
df = pd.read_csv(url, encoding = "latin1")

# then view the columns of this dataframe, this will help us get familiar with the dataset before working on it
df.columns.values.tolist()

['Year',
 'Org Name',
 'Org Code',
 'Spec Ed. Grad Rate - Grad Cohort #',
 'Spec Ed. Grad Rate - Grad #',
 'Spec Ed. Grad Rate - Grad %',
 'Spec Ed. Dropout - Enr #',
 'Spec Ed. Dropout - Drop #',
 'Spec Ed. Dropout - Drop %',
 'LRE Ages 6-21 - Students #',
 'LRE Ages 6-21 - Full Incl #',
 'LRE Ages 6-21 - Full Incl %',
 'LRE Ages 3-5 - Students #',
 'LRE Ages 3-5 - Full Incl #',
 'LRE Ages 3-5 - Full Incl %',
 'Cohort Completion Year',
 'Substantial growth of knowledge & skills',
 'Survey Period',
 'Surv Meet Std #',
 'Surv Meet Std %',
 'Sch Yr Rev',
 '# of Students Engaged',
 'Dist Rate']

In [ ]:
# We will then load the first 5 rows of our data and try to understand it more, while noting the missing values in the records, 
# afterwards learn more about the parameters
# 
df.head()

   Year  Org Name  Org Code  ... Sch Yr Rev # of Students Engaged Dist Rate
0  2012  Abington     10000  ...    2010-11                     8      100%
1  2013  Abington     10000  ...    2010-11                     8      100%
2  2012     Acton     20000  ...    2012-13                    NR        NR
3  2013     Acton     20000  ...    2012-13                    NR        NR
4  2012  Acushnet     30000  ...    2011-12                   NaN

[5 rows x 23 columns]

**i) na_values**

The na_values parameter will allow us to specify additional missing or NaN values. What are NaN values you ask?

> *These NaN values are from the python numpy library - Missing values in python are displayed in a few ways - NaN, NAN or nan and are all equivalent.*

By default, this parameter is usually never used when reading the file mainly because these default missing values - NaN or nan, are already available.

In [ ]:
# now we load the data with the default values
print(pd.read_csv(url, encoding = 'latin1').head())

   Year  Org Name  Org Code  ... Sch Yr Rev # of Students Engaged Dist Rate
0  2012  Abington     10000  ...    2010-11                     8      100%
1  2013  Abington     10000  ...    2010-11                     8      100%
2  2012     Acton     20000  ...    2012-13                    NR        NR
3  2013     Acton     20000  ...    2012-13                    NR        NR
4  2012  Acushnet     30000  ...    2011-12                   NaN

[5 rows x 23 columns]

**ii) keep_default_na**

The second parameter is the `keep_default_na` parameter, which is a bool (boolean). It allows us to specify whether any additional values need to be considered missing. By default this parameter is True, meaning any additional missing values specified with the na_values paramenter will be appended to list of missing values. 

We can also set `keep_default_na=False` which will mean that we will only use missing values specified in na_values.

In [ ]:
# Example 2
# We then load the data without default missing values 
# 
print(pd.read_csv(url, encoding = 'latin1', keep_default_na = False).head())

   Year  Org Name  Org Code  ... Sch Yr Rev # of Students Engaged Dist Rate
0  2012  Abington     10000  ...    2010-11                     8      100%
1  2013  Abington     10000  ...    2010-11                     8      100%
2  2012     Acton     20000  ...    2012-13                    NR        NR
3  2013     Acton     20000  ...    2012-13                    NR        NR
4  2012  Acushnet     30000  ...    2011-12

[5 rows x 23 columns]

In [ ]:
# Challenge 1: 
# Using the keep_default_na parameter, load the data with the default missing values below
# 
print(pd.read_csv(url, encoding='latin1').head())

   Year  Org Name  Org Code  ... Sch Yr Rev # of Students Engaged Dist Rate
0  2012  Abington     10000  ...    2010-11                     8      100%
1  2013  Abington     10000  ...    2010-11                     8      100%
2  2012     Acton     20000  ...    2012-13                    NR        NR
3  2013     Acton     20000  ...    2012-13                    NR        NR
4  2012  Acushnet     30000  ...    2011-12                   NaN

[5 rows x 23 columns]

iii) **na_filter**

Our third parameter is the *na_filter parameter,* which is a bool that specifies whether any values will be read as missing. By default the na_filter=True, meaning that missing values will be coded as NaN. If na_filter=False, then nothing will be recorded as missing. We normally use this parameter when we want to set false the na_values and keep_default_na parameter all at the same time as well as when we want to quickly load any data without missing values.

In [ ]:
# Example 3
# Let's set the na_filter parameter to True
# 
print(pd.read_csv(url, na_filter = True, encoding ='latin1').head(10))

   Year  Org Name  Org Code  ... Sch Yr Rev # of Students Engaged Dist Rate
0  2012  Abington     10000  ...    2010-11                     8      100%
1  2013  Abington     10000  ...    2010-11                     8      100%
2  2012     Acton     20000  ...    2012-13                    NR        NR
3  2013     Acton     20000  ...    2012-13                    NR        NR
4  2012  Acushnet     30000  ...    2011-12                   NaN
5  2013  Acushnet     30000  ...    2011-12                   NaN
6  2012    Agawam     50000  ...    2009-10                    14      100%
7  2013    Agawam     50000  ...    2009-10                    14      100%
8  2012  Amesbury     70000  ...    2010-11                     7    87.50%
9  2013  Amesbury     70000  ...    2010-11                     7    87.50%

[10 rows x 23 columns]

In [ ]:
# Challenge 2
# Now let's see what happens when we set the na_filter parameter to False
# 
print(pd.read_csv(url, encoding='latin1',na_filter=False).head(10))

   Year  Org Name  Org Code  ... Sch Yr Rev # of Students Engaged Dist Rate
0  2012  Abington     10000  ...    2010-11                     8      100%
1  2013  Abington     10000  ...    2010-11                     8      100%
2  2012     Acton     20000  ...    2012-13                    NR        NR
3  2013     Acton     20000  ...    2012-13                    NR        NR
4  2012  Acushnet     30000  ...    2011-12
5  2013  Acushnet     30000  ...    2011-12
6  2012    Agawam     50000  ...    2009-10                    14      100%
7  2013    Agawam     50000  ...    2009-10                    14      100%
8  2012  Amesbury     70000  ...    2010-11                     7    87.50%
9  2013  Amesbury     70000  ...    2010-11                     7    87.50%

[10 rows x 23 columns]

## 1.1 Merging Data

Missing data can also result from the merging of datasets. This we will see when we create a merged table from the two datasets below. 

Having missing values in the merged table can be as a result of either or neither of the datasets having any missing values i.e. if the datasets have unique columns.

In [ ]:
apple_orange_dataset = 'http://bit.ly/AppleOrangeDataSet'
stability_dataset    = 'http://bit.ly/StabilityDataset'

apple_orange_dataset = pd.read_csv(apple_orange_dataset, encoding ='latin1')
stability_dataset    = pd.read_csv(stability_dataset, encoding ='latin1')

The appleorange dataset  contains production volumes of apples and oranges while the stability dataset contains country stability indicators.

In [ ]:
# Displaying our the first dataset
#
apple_orange_dataset.head(10)

                             FAOSTAT 2013  ... Unnamed: 5
0                              Elements Ê  ...     2009.0
1  Food supply quantity (tonnes) (tonnes)  ...        NaN
2  Food supply quantity (tonnes) (tonnes)  ...        NaN
3  Food supply quantity (tonnes) (tonnes)  ...        NaN
4                                 Albania  ...        NaN
5  Food supply quantity (tonnes) (tonnes)  ...        NaN
6                                 Albania  ...        NaN
7  Food supply quantity (tonnes) (tonnes)  ...        NaN
8                                 Algeria  ...        NaN
9  Food supply quantity (tonnes) (tonnes)  ...        NaN

[10 rows x 6 columns]

In [ ]:
# Displaying our second dataset
# 
stability_dataset.head(10)

    FAOSTAT 2013 Unnamed: 1  ...       Unnamed: 4  Unnamed: 5
0     Elements Ê        NaN  ...          Items Ê      2009.0
1  Value (index)        NaN  ...              NaN         NaN
2  Value (index)        NaN  ...              NaN         NaN
3  Value (index)        NaN  ...              NaN         NaN
4    Afghanistan          2  ...  -2.70, index ()         NaN
5  Value (index)        NaN  ...              NaN         NaN
6        Albania          3  ...  -0.05, index ()         NaN
7  Value (index)        NaN  ...              NaN         NaN
8        Algeria          4  ...  -1.23, index ()         NaN
9  Value (index)        NaN  ...              NaN         NaN

[10 rows x 6 columns]

In [ ]:
# Now merging the two dataframes and analysing the output
merged_dataset = apple_orange_dataset.merge(stability_dataset, left_on='FAOSTAT 2013', right_on='FAOSTAT 2013')

# Displayig our dataset
merged_dataset.head(20)

           FAOSTAT 2013  ... Unnamed: 5_y
0            Elements Ê  ...       2009.0
1               Albania  ...          NaN
2               Albania  ...          NaN
3               Albania  ...          NaN
4               Albania  ...          NaN
5               Albania  ...          NaN
6               Albania  ...          NaN
7               Algeria  ...          NaN
8               Algeria  ...          NaN
9               Algeria  ...          NaN
10              Algeria  ...          NaN
11              Algeria  ...          NaN
12              Algeria  ...          NaN
13               Angola  ...          NaN
14               Angola  ...          NaN
15               Angola  ...          NaN
16               Angola  ...          NaN
17  Antigua and Barbuda  ...          NaN
18  Antigua and Barbuda  ...          NaN
19  Antigua and Barbuda  ...          NaN

[20 rows x 11 columns]

In [ ]:
# Challenge 4:
# Merge the following two manifesto project datasets and 
# discuss with your peer on origin of the missing values in the merged dataset
#
party_names_dataset  = 'http://bit.ly/PartyNamesMarporDataSet'
party_names_dataset2 = 'http://bit.ly/PartyNamesPledges'
data1=pd.read_csv(party_names_dataset, encoding="latin1")
data1.head()
data2=pd.read_csv(party_names_dataset2, encoding="latin1")
data2.head()
data1.merge(data2,how='inner',on ='name')

KeyError: ignored

## 1.2 User Input Values

Missing values within a dataset can also result from mistakes from the user during the data entry/collection phase. This could also result from creating a vector of values from a calculation or from manually curating a vector as shown in the examples below.

In [ ]:
# Importing nan from numpy so as to represent missing values
#
from numpy import nan

In [ ]:
# Creating a missing value in a series
# NB: Series is the datastructure for a single column of a DataFrame. 
# 
population = pd.Series({'Kenya': 47, 'Tanzania': nan, 'Uganda': 30})

# Lets now print. Note that NaNs are also valid values for both Series and DataFrames
#
print(population)

Kenya       47.0
Tanzania     NaN
Uganda      30.0
dtype: float64

In [ ]:
# Challenge 5:
# Create a series with the names and ages of your peers. Note nan for the ages of peers who you don't know.
# 
peers= pd.Series({'claire': 20, 'Brian':nan,'cyril':22})
peers

claire    20.0
Brian      NaN
cyril     22.0
dtype: float64

In [ ]:
# Now creating a missing value in a dataframe
list_data = [['Steve', 56, 'Nairobi', 'no'],['Bill', 57, 'Machackos', 'yes'],['Richard', nan, nan, 'yes']]

# Defining our columns
age_df = pd.DataFrame(list_data, columns=['Name', 'Age', 'Hometown', 'Public Commute'])

# Printing age_df
age_df

      Name   Age   Hometown Public Commute
0    Steve  56.0    Nairobi             no
1     Bill  57.0  Machackos            yes
2  Richard   NaN        NaN            yes

In [ ]:
# We can also assign a column of missing values to a dataframe directly
#
age_df['Public Commute'] = 'Yes';

# print age_df
#
print(age_df)

      Name   Age   Hometown Public Commute
0    Steve  56.0    Nairobi            Yes
1     Bill  57.0  Machackos            Yes
2  Richard   NaN        NaN            Yes

In [ ]:
# Challenge 6
# Create a dataframe with a list of your country's presidents 
# with their no. of years in office and their last year in office. 
# NB: You do not know the last year of office for the current president. 
#
presidents= [['Moi',25,2002],['Kibaki',10,2013],['Uhuru',10,'nan']]
presidents_df= pd.DataFrame(presidents, columns= ['President', 'No_of_years','Last_year_in_office'])
presidents_df

  President  No_of_years Last_year_in_office
0       Moi           25                2002
1    Kibaki           10                2013
2     Uhuru           10                 nan

## 1.3 Re-indexing

Missing values in data can also be introduced when we reindex our dataframe. We will show this through  a dataset from Gapminder.

In [ ]:
# Getting our dataset
gapminder_dataset    = 'http://bit.ly/GapMinderKenyaDataSet'
gapminder_dataset_df = pd.read_csv(gapminder_dataset, encoding ='latin1')

# printing the dataframe
print(gapminder_dataset_df)

   country continent  year  lifeExp       pop    gdpPercap
0    Kenya    Africa  1952   42.270   6464046   853.540919
1    Kenya    Africa  1957   44.686   7454779   944.438315
2    Kenya    Africa  1962   47.949   8678557   896.966373
3    Kenya    Africa  1967   50.654  10191512  1056.736457
4    Kenya    Africa  1972   53.559  12044785  1222.359968
5    Kenya    Africa  1977   56.155  14500404  1267.613204
6    Kenya    Africa  1982   58.766  17661452  1348.225791
7    Kenya    Africa  1987   59.339  21198082  1361.936856
8    Kenya    Africa  1992   59.285  25020539  1341.921721
9    Kenya    Africa  1997   54.407  28263827  1360.485021
10   Kenya    Africa  2002   50.992  31386842  1287.514732
11   Kenya    Africa  2007   54.110  35610177  1463.249282

In [ ]:
# now performing a groupby operation so as to subset the data
life_exp = gapminder_dataset_df.groupby(['year'])['lifeExp'].mean()
print(life_exp)

year
1952    42.270
1957    44.686
1962    47.949
1967    50.654
1972    53.559
1977    56.155
1982    58.766
1987    59.339
1992    59.285
1997    54.407
2002    50.992
2007    54.110
Name: lifeExp, dtype: float64

In [ ]:
# We then reindexing by slicing the data. We continue to chain the 'loc' from the code above
print(life_exp.loc[range(2000, 2007)])

Now, it seems we have been provided a suggestion to use the reindex() method. We will do this below as we choose to subset the data separately and then use the reindex() method.

In [ ]:
# subsetting the dataframe
y_2000_df = life_exp[life_exp.index > 2000] 
print(y_2000_df)

year
2002    50.992
2007    54.110
Name: lifeExp, dtype: float64

In [ ]:
# then reindexing
print(y_2000_df.reindex(range(2000, 2010)))

year
2000       NaN
2001       NaN
2002    50.992
2003       NaN
2004       NaN
2005       NaN
2006       NaN
2007    54.110
2008       NaN
2009       NaN
Name: lifeExp, dtype: float64

In [ ]:
     # Challenge 7
# We would want to look at only the years from 2000 to 2010 from the gapminder dataset below. 
# Perform grouped operations, subseting the data and then re-indexing it. 
# Show how this process might result to getting missing values.

# Assinging data the url for our dataset
data = 'http://bit.ly/GapMinderUgandaDataSet'

dat1= pd.read_csv(data)
y_2000_df = dat1[data1.index (range(2000,2010))]